# Site settings
title: Pete Ashton's Art
subtitle: Digital images are weird. Let's make art about them. 
email: pete@peteashton.com
description: Pete Ashton I’m an artist based in Birmingham in the North West of Europe. <br/>His work centers on cameras as post-photographic data-capture devices with an interest in realising their output through mechanical/human gesture.<br/>This site archives key works from the last few years.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://peteash10.github.io" # the base hostname & protocol for your site


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 12

# Social settings
github_url: https://github.com/peteash10
instagram_url: https://www.instagram.com/peteashton/
twitter_url: https://twitter.com/peteashton

# Build settings
markdown: kramdown
