# Site settings
title: Pete Ashton's Art
subtitle:  
email: pete@peteashton.com
phone: +44 7775 690106
description: Digital images are weird. I make art about them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://art.peteashton.com" # the base hostname & protocol for your site


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 30

# Social settings
github_url: https://github.com/peteash10
instagram_url: https://www.instagram.com/peteashton/
twitter_url: https://twitter.com/peteashton

# Build settings
markdown: kramdown

gems:
  - jekyll-archives
  
  jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
